spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: vvo.082015@gmail.com
    password: valya_24
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false